services:
  mongo:
    image: mongo:6
    command: [ "--replSet", "rs0", "--bind_ip_all", "--port", "27017" ]
    ports:
      - "27017:27017"
    healthcheck:
      test: test $$(mongosh --port 27017 --quiet --eval "try {rs.initiate({_id:'rs0',members:[{_id:0,host:\"localhost:27017\"}]})} catch(e) {rs.status().ok}") -eq 1
      interval: 10s
      start_period: 30s

  redis:
    image: redis:7.4
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:4.1
    ports:
      - "5672:5672"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5433:5432"